name: doc
channels:
- defaults
- conda-forge
- bioconda
dependencies:
- alabaster
- asn1crypto
- babel
- ca-certificates
- certifi
- cffi
- chardet
- cmake
- commonmark
- cryptography
- cython==0.23.4
- docutils
- future
- gsl
- idna
- imagesize
- ipykernel
- jinja2
- jupyter
- libedit
- libffi
- libgcc-ng # Linux only
- libstdcxx-ng # Linux only
- libtool
- markupsafe
- matplotlib
- mkl
- ncurses=5.9
- nest
- numpy
- numpydoc
- openblas
- openmpi>=2.1
- openssl
- path.py
- pillow
- pip
- pycparser
- pydot
- pygments
- PyHamcrest
- pyopenssl
- pysocks
- pytest
- python==3.5
- pytz
- readline==6.2*
- requests
- setuptools
- scipy
- six
- snowballstemmer
- sphinx==1.5.6
- sphinxcontrib
- sphinxcontrib-websupport
- sphinx_rtd_theme
- sqlite
- statsmodels
- tk
- typing
- urllib3
- wheel
- xz
- zlib
- pip:
  - example
  - Image
  - nbsphinx
  - recommonmark==0.4.0
  - seaborn
  - sphinx_gallery
  - sphinxcontrib-napoleon
  - mock
  - helper
  - network

