name: nest
channels:
   - steffengraber
   - conda-forge
   - defaults
dependencies:
- cmake
- cython ==0.23.4
- docutils
- future
- gcc_linux-64
- gxx_linux-64
- gsl
- icu
- jsoncpp
- libtool
- matplotlib
- mpi4py
- mkl
- ncurses
- nest ==2.16.0
- numpy
- numpydoc
- openblas
- openmpi
- pandas
- path.py
- python ==3.5
- pyqt
- readline ==6.2*
- scipy
- setuptools
- statsmodels
- alabaster
- babel
- chardet
- commonmark
- imagesize
- jinja2
- markupsafe
- pygments
- snowballstemmer
- sphinx==1.5.6
- sphinxcontrib
- sphinxcontrib-websupport
- sphinx_rtd_theme
- pip:
   - example
   - helper
   - Image
   - network
   - recommonmark
   - sphinx_gallery
